<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260807150000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the baseline dog and treatment schema';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'Migration can only be executed safely on PostgreSQL.',
        );

        $this->addSql('CREATE TABLE dog (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, gender VARCHAR(255) DEFAULT NULL, birth_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, adopt_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, weight INT DEFAULT NULL, height INT DEFAULT NULL, status VARCHAR(100) DEFAULT NULL, avatar VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE treatment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type TEXT NOT NULL, product_name VARCHAR(255) NOT NULL, treatment_date DATE NOT NULL, due_date DATE DEFAULT NULL, note VARCHAR(255) DEFAULT NULL, dog_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_98013C31634DFEB ON treatment (dog_id)');
        $this->addSql('ALTER TABLE treatment ADD CONSTRAINT FK_98013C31634DFEB FOREIGN KEY (dog_id) REFERENCES dog (id) ON DELETE RESTRICT NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'Migration can only be executed safely on PostgreSQL.',
        );

        $this->addSql('ALTER TABLE treatment DROP CONSTRAINT FK_98013C31634DFEB');
        $this->addSql('DROP TABLE treatment');
        $this->addSql('DROP TABLE dog');
    }
}
