<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260807150000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the complete dogs diary baseline schema';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'Migration can only be executed safely on PostgreSQL.',
        );

        $this->addSql('CREATE TABLE dog (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, gender VARCHAR(255) DEFAULT NULL, birth_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, adopt_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, weight INT DEFAULT NULL, height INT DEFAULT NULL, status VARCHAR(100) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE treatment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type TEXT NOT NULL, product_name VARCHAR(255) NOT NULL, treatment_date DATE NOT NULL, due_date DATE DEFAULT NULL, note VARCHAR(255) DEFAULT NULL, dog_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql("CREATE TABLE dog_media (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, dog_id INT NOT NULL, media_type VARCHAR(255) NOT NULL, storage_key VARCHAR(255) NOT NULL, original_name VARCHAR(255) NOT NULL, mime_type VARCHAR(100) NOT NULL, size_bytes BIGINT NOT NULL, width INT DEFAULT NULL, height INT DEFAULT NULL, is_thumbnail BOOLEAN DEFAULT FALSE NOT NULL, is_profile BOOLEAN DEFAULT FALSE NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (id), CONSTRAINT CHK_DOG_MEDIA_TYPE CHECK (media_type IN ('image', 'video')), CONSTRAINT CHK_DOG_MEDIA_THUMBNAIL_TYPE CHECK (is_thumbnail = FALSE OR media_type = 'image'), CONSTRAINT CHK_DOG_MEDIA_TEXT_METADATA CHECK (btrim(storage_key) <> '' AND btrim(original_name) <> '' AND btrim(mime_type) <> '' AND ((media_type = 'image' AND mime_type LIKE 'image/%') OR (media_type = 'video' AND mime_type LIKE 'video/%'))), CONSTRAINT CHK_DOG_MEDIA_SIZE CHECK (size_bytes > 0), CONSTRAINT CHK_DOG_MEDIA_DIMENSIONS CHECK (((width IS NULL AND height IS NULL) OR (width > 0 AND height > 0)) AND (media_type <> 'image' OR (width IS NOT NULL AND height IS NOT NULL))))");
        $this->addSql("CREATE TABLE treatment_media (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, treatment_id INT NOT NULL, storage_key VARCHAR(255) NOT NULL, original_name VARCHAR(255) NOT NULL, mime_type VARCHAR(100) NOT NULL, size_bytes BIGINT NOT NULL, width INT NOT NULL, height INT NOT NULL, position SMALLINT NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (id), CONSTRAINT CHK_TREATMENT_MEDIA_TEXT CHECK (btrim(storage_key) <> '' AND btrim(original_name) <> '' AND mime_type LIKE 'image/%'), CONSTRAINT CHK_TREATMENT_MEDIA_SIZE CHECK (size_bytes > 0 AND width > 0 AND height > 0), CONSTRAINT CHK_TREATMENT_MEDIA_POSITION CHECK (position BETWEEN 1 AND 5))");
        $this->addSql('CREATE INDEX IDX_98013C31634DFEB ON treatment (dog_id)');
        $this->addSql('CREATE INDEX IDX_DOG_MEDIA_DOG_CREATED ON dog_media (dog_id, created_at)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DOG_MEDIA_STORAGE_KEY ON dog_media (storage_key)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DOG_MEDIA_THUMBNAIL ON dog_media (dog_id) WHERE is_thumbnail = TRUE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DOG_MEDIA_PROFILE ON dog_media (dog_id) WHERE is_profile = TRUE');
        $this->addSql('CREATE INDEX IDX_TREATMENT_MEDIA_TREATMENT_CREATED ON treatment_media (treatment_id, created_at)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_TREATMENT_MEDIA_STORAGE_KEY ON treatment_media (storage_key)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_TREATMENT_MEDIA_POSITION ON treatment_media (treatment_id, position)');
        $this->addSql('ALTER TABLE treatment ADD CONSTRAINT FK_98013C31634DFEB FOREIGN KEY (dog_id) REFERENCES dog (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dog_media ADD CONSTRAINT FK_DOG_MEDIA_DOG FOREIGN KEY (dog_id) REFERENCES dog (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE treatment_media ADD CONSTRAINT FK_TREATMENT_MEDIA_TREATMENT FOREIGN KEY (treatment_id) REFERENCES treatment (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'Migration can only be executed safely on PostgreSQL.',
        );

        $this->addSql('DROP TABLE treatment_media');
        $this->addSql('DROP TABLE dog_media');
        $this->addSql('DROP TABLE treatment');
        $this->addSql('DROP TABLE dog');
    }
}
