<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260819145346 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create users and the many-to-many dog ownership relation';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'Migration can only be executed safely on PostgreSQL.',
        );

        $this->addSql('CREATE TABLE app_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_APP_USER_EMAIL ON app_user (email)');
        $this->addSql('CREATE TABLE dog_owner (dog_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (dog_id, user_id))');
        $this->addSql('CREATE INDEX IDX_54C6AF39634DFEB ON dog_owner (dog_id)');
        $this->addSql('CREATE INDEX IDX_54C6AF39A76ED395 ON dog_owner (user_id)');
        $this->addSql('ALTER TABLE dog_owner ADD CONSTRAINT FK_54C6AF39634DFEB FOREIGN KEY (dog_id) REFERENCES dog (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dog_owner ADD CONSTRAINT FK_54C6AF39A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'Migration can only be executed safely on PostgreSQL.',
        );

        $this->addSql('DROP TABLE dog_owner');
        $this->addSql('DROP TABLE app_user');
    }
}
